- src/rtlib.jl
> Disallow runtime code emission to recurse into itself.

- src/driver.jl
- src/mcgen.jl
- src/rtlib.jl
https://github.com/JuliaGPU/GPUCompiler.jl/pull/2/
> Extract some bits from the AMDGPU PR

- .gitignore
- .travis.yml
- Project.toml
- test/Project.toml
- test/codegen/native.jl
- test/definitions/native.jl
- test/lit.cfg.py
- test/runtests.jl
Creating the infrastructure for this took me more time
than I would like to admit, but at least this allows us
to add tests that use `lit`. Right now there is only a
simple example. 
Let me know what you think about the structure and naming
of the files.
> Add support for using lit tests

- src/irgen.jl
> Use the new codegen policy for exhaustive compilation.

- Manifest.toml
- Project.toml
- src/optim.jl
- src/runtime.jl
- src/validation.jl
- test/definitions/gcn.jl
- test/definitions/native.jl
- test/definitions/ptx.jl
- test/gcn.jl
- test/native.jl
- test/ptx.jl
- test/util.jl
Adapts to https://github.com/JuliaLang/julia/pull/35645
> Adapt to removal of address spaces

- src/validation.jl
Adapts to JuliaLang/julia#35347
> Fix non-isbits argument validation.

- src/gcn.jl
- src/irgen.jl
Added v_readfirstlane_b32 workaround to GCN
> Abstract out emit_trap!

- test/gcn.jl
I completely forgot to add this in the original PR :disappointed:
> Add test for GCN's custom emit_trap

- src/driver.jl
- src/interface.jl
- test/common.jl
- test/runtests.jl
Also adds tests for `compile()` output
> Return undefined globals from compile()

- src/irgen.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/59
```
julia> CUDA.GPUCompiler.mangle_call(sin, NTuple{3, CuDeviceArray{Float32,2,CUDA.AS.Global}})
"_Z3sin13CuDeviceArrayI7Float32Li2E6GlobalE13CuDeviceArrayI7Float32Li2E6GlobalE13CuDeviceArrayI7Float32Li2E6GlobalE"
```
```
julia> GPUCompiler.mangle_call(sin, NTuple{3, CuDeviceArray{Float32,2,CUDA.AS.Global}})
"_Z3sin13CuDeviceArrayI7Float32Li2E6GlobalES_IS0_Li2ES1_ES_IS0_Li2ES1_E"
```
```
$ echo _Z3sin13CuDeviceArrayI7Float32Li2E6GlobalES_IS0_Li2ES1_ES_IS0_Li2ES1_E | c++filt                                                                                          [tb/mangle_substitutions] 
sin(CuDeviceArray<Float32, 2, Global>, CuDeviceArray<Float32, 2, Global>, CuDeviceArray<Float32, 2, Global>)
```
> Use substitutions when mangling as C++.

- res/pygments/ptx.py
- src/driver.jl
- src/interface.jl
- src/ptx.jl
- src/reflection.jl
> Add support for highlighting PTX with Pygments.

- src/irgen.jl
Fixes https://github.com/maleadt/LLVM.jl/issues/201
> Sanitize all function names again.

- Project.toml
> bump DataStructures version

- src/irgen.jl
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/434
> Catch some additional early errors.

- src/rtlib.jl
Should fix https://github.com/JuliaGPU/CUDA.jl/issues/293
> Retry runtime library compilation if it failed to load.

- src/spirv.jl
- test/spirv.jl
Its compiler can only handle byval on struct arguments (intel/compute-runtime#341).
> Work around Intel driver issue with byval.

- src/error.jl
- src/optim.jl
- src/validation.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/105
> Various error-path fixes

- .buildkite/pipeline.yml
- src/reflection.jl
- src/spirv.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/115
> SPIRV debug improvements

- src/rtlib.jl
https://github.com/JuliaGPU/GPUCompiler.jl/pull/82#issuecomment-733116035
> Use Base.rename instead of mv for atomicity.

- src/gcn.jl
- src/interface.jl
- src/irgen.jl
- src/ptx.jl
- src/spirv.jl
- test/native.jl
- test/spirv.jl
Have it called on every entry-point.
Use that to expose device functions to CUDA callers.
> Generalize kernel processing.

- src/driver.jl
The goal would be for downstream packages to build their own chain of `emit` functions instead of returning more and more from `codegen` (undefined functions, undefined globals, what's next).
> Split the codegen function in separate emission steps.

- src/cache.jl
Following https://github.com/JuliaGPU/GPUCompiler.jl/pull/140, now that we pass the actual CompilerJob around, that can be used to encode all properties of the job and we shouldn't forward `kwargs` anymore. This simplifies the CodeInfo generator. cc @jpsamaroo
> Remove kwarg forwarding from the compiler cache.

- src/gcn.jl
- src/interface.jl
- src/jlgen.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/153
> Add Julia's non-integral pointers to the datalayout.

- src/cache.jl
- src/driver.jl
- src/interface.jl
#160 had introduced https://github.com/JuliaGPU/CUDA.jl/issues/815
> Hack around incomplete world age handling.

- src/driver.jl
- src/interface.jl
- src/irgen.jl
- src/jlgen.jl
- src/ptx.jl
- src/validation.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/173.
> Use the GPU abstract interpreter for kernel validation

- src/bpf.jl
- test/bpf.jl
> Don't do finish_module in BPF backend

- src/gcn.jl
- test/gcn.jl
After this is merged we should tag.
> [GCN] Make sure we are not breaking the interface

- src/optim.jl
- test/runtests.jl
cc @vchuravy @jpsamaroo, this disables tests that need to be adapted.
> Fixes for 1.7

- src/jlgen.jl
Not sure if I need a lock, but it sounds like the fact that we've taken the codegen lock means we're already accessing the global exclusively?
Fixes #187
> Workaround cfunction closures on non-x86

- test/gcn.jl
- test/runtests.jl
I didn't really care about all those assembly details in the first place.
> Re-enable GCN tests

- src/jlgen.jl
- test/native.jl
Without checking for existance of the LLVM function GPUCompiler will error on the test case below.
> Fix llvm function map emission

- test/runtests.jl
https://github.com/JuliaRegistries/General/pull/38545
> Re-enable testing of the SPIRV back-end on Julia 1.7.

- Manifest.toml
- src/GPUCompiler.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/214
> Only import from ExprTools what we need.

- src/jlgen.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/218
> Prevent against recursion during invalidation.

- Manifest.toml
- Project.toml
- src/debug.jl
- src/driver.jl
- src/gcn.jl
- src/interface.jl
- src/irgen.jl
- src/mcgen.jl
- src/native.jl
- src/optim.jl
- src/ptx.jl
- src/rtlib.jl
- src/runtime.jl
- src/spirv.jl
- test/definitions/native.jl
https://github.com/maleadt/LLVM.jl/pull/240
> Adapt to LLVM changes.

- src/driver.jl
Just found this typo but I'm still trying to understand the project and I'm not sure about the best way to create the test-cases...
> Fix Julia IR emission in codegen()

- src/optim.jl
> Actually use our own opt pipeline.

- examples/kernel.jl
- test/util.jl
We have contextual dispatch now, and don't do this kind of detection anymore.
> Remove unneeded test methods.

- src/GPUCompiler.jl
- src/utils.jl
Since `Base.ttyhascolor` may yield.
> Detect stderr ttyhascolor at init

- src/irgen.jl
It is now done before optimization.
> Don't separately optimize byval-lowered code.

- src/spirv.jl
As seen in https://github.com/JuliaGPU/GPUArrays.jl/pull/387, optimization can introduce `freeze`.
> Clean-up LLVM for SPIR-V before mcgen.

- src/irgen.jl
- src/spirv.jl
But remove dbg instructions before doing so.
I knew https://github.com/JuliaGPU/GPUCompiler.jl/pull/285 was too easy.
> Clone with global changes on LLVM 12.

- src/gcn.jl
Otherwise the saved runtime has the wrong one, causing warnings.
> Change the GCN triple at the start of optimization.

- src/irgen.jl
- src/optim.jl
- src/ptx.jl
- src/reflection.jl
- src/reflection_compat.jl
- src/rtlib.jl
- src/spirv.jl
- src/validation.jl
- test/Project.toml
- test/native.jl
> Cleanup 0.15

- src/irgen.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/325
> Name mangling fixes and improvements

- src/interface.jl
- src/metal.jl
- src/validation.jl
Closes https://github.com/JuliaGPU/Metal.jl/issues/25
> Add support for custom IR validation passes.

- src/driver.jl
- src/precompile.jl
Required for https://github.com/EnzymeAD/Enzyme.jl/issues/375
> Don't run global opt when opt disabled

- src/jlgen.jl
- test/native.jl
Adapts to https://github.com/JuliaLang/julia/pull/46203
> Access code instance fields atomically.

- src/irgen.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/464
It's possible this breaks cases where we were linking multiple modules, but it's problematic if that relies on identical renames of declarations and definitions, so may be better to fix at that end.
> Don't rename function declarations, only definitions.

- src/reflection.jl
This is my first time trying the GitHub online version of VS Code. I hope this PR turned out ok.
> Add missing backticks

- src/jlgen.jl
Addresses https://github.com/JuliaGPU/GPUCompiler.jl/pull/567#discussion_r1567162490
> Don't opt into typeinf tracking before v1.11

- src/validation.jl
- test/native_tests.jl
Closes https://github.com/JuliaGPU/CUDA.jl/issues/2514
> Extend non-isbits argument error text.

- src/reflection.jl
Addresses https://github.com/JuliaGPU/GPUCompiler.jl/pull/668#discussion_r2013968869
> Pass optimize kwarg from code_llvm to CompilerConfig.
