JuliaGPU/GPUCompiler.jl

- src/rtlib.jl
Might not exist in fresh depots running with --compiled-modules=no
> Use mkpath instead of mkdir to create the rtlib cache dir.

- .gitlab-ci.yml
- src/GPUCompiler.jl
- src/gcn.jl
- test/gcn.jl
- test/runtests.jl
> Add GCN compiler target

- src/GPUCompiler.jl
- src/execution.jl
Used by CUDAnative and AMDGPUnative.
@jpsamaroo I slightly changed 'split_kwargs!' so you pass in the kwarg groups instead.
> Add some execution-related macro utilities.

- src/irgen.jl
Will be superseded by https://github.com/JuliaGPU/GPUCompiler.jl/pull/16, but I doubt we want to go 1.5-only right now.
> Adapt kernel wrapperr to 1.5 argument passing changes.

- src/driver.jl
- src/error.jl
- src/gcn.jl
- src/interface.jl
- src/irgen.jl
- src/mcgen.jl
- src/native.jl
- src/optim.jl
- src/ptx.jl
- src/reflection.jl
- src/rtlib.jl
- src/validation.jl
- test/definitions/gcn.jl
- test/definitions/native.jl
- test/definitions/ptx.jl
- test/util.jl
Basically, use a concrete `CompilerJob` that's parameterized both on `CompilerTarget` (defined in GPUCompilers.jl) and a `CompilerParams` (for external packages). Makes it much cleaner to extent.
The only remaining ugly part is when extending an interface that already has an implementation in GPUCompilers.jl:
```julia
struct CUDACompilerParams <: AbstractCompilerParams end
CUDACompilerJob = CompilerJob{PTXCompilerTarget,CUDACompilerParams}
function GPUCompiler.process_module!(job::CUDACompilerJob, mod::LLVM.Module)
invoke(GPUCompiler.process_module!,
Tuple{CompilerJob{PTXCompilerTarget}, typeof(mod)},
job, mod)
emit_exception_flag!(mod)
end
```
But maybe that's just a badly designed interface.
> Redesign the compiler interfaces yet again.

- .gitlab-ci.yml
- .travis.yml
- Project.toml
- src/ptx.jl
- test/ptx.jl
PTX_Kernel | PTX_Kernel - Call to a PTX kernel.  Passes all arguments in parameter space.
-- | --
PTX_Device | PTX_Device - Call to a PTX device function.  Passes all arguments in register or parameter space.
> Use appropriate calling conventions for PTX functions and kernels.

- src/driver.jl
- src/interface.jl
- src/rtlib.jl
They should match the definitions.
Also emit without optimization, or address spaces would be stripped on 1.5+
> Check the types of emitted runtime functions.

- src/gcn.jl
- src/interface.jl
- src/irgen.jl
- src/ptx.jl
For the AMDGPU target, the `byval` attribute is not (yet) valid for kernel arguments, so the removal of the `wrap_entry!` functionality in #16 broke the GCN compiler by making the target emit code expecting a pointer instead of an inlined struct. This PR pulls back in the logic for `wrap_entry` just for GCN, and replaces usage of `byval`, until the AMDGPU target has gotten `byval` working again.
> Disable byval for GCN kernels

- .gitlab-ci.yml
- src/cache.jl
I think this was the cause for nonsensical stack traces like:
```
Error During Test at /builds/JuliaGPU/CUDA.jl/test/device/cuda.jl:907
Got exception outside of a @test
CUDA error: out of memory (code 2, ERROR_OUT_OF_MEMORY)
Stacktrace:
[1] throw_api_error(::CUDA.cudaError_enum) at /builds/JuliaGPU/CUDA.jl/lib/cuda/error.jl:103
[2] CuModule(::Array{UInt8,1}, ::Dict{CUDA.CUjit_option_enum,Any}) at /builds/JuliaGPU/CUDA.jl/lib/cuda/module.jl:42
[3] CuModule(::CuLinkImage, ::Dict{CUDA.CUjit_option_enum,Any}) at /builds/JuliaGPU/CUDA.jl/lib/cuda/module/linker.jl:142
[4] _cufunction(::GPUCompiler.FunctionSpec{var"#3908#kernel#593",Tuple{}}; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /builds/JuliaGPU/CUDA.jl/src/compiler/execution.jl:335
[5] _cufunction at …
```
> Avoid OOB linetable access on pre-1.5.

- src/irgen.jl
- test/native.jl
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/54.
@jpsamaroo the GCN compiler has similar functionality, I suppose we can merge this now. But do you really need to rewrite all those exceptions (e.g. `julia_bounds_error`)? Those just work for CUDA.
> Support lowering non-runtime throw functions.

- src/driver.jl
- src/reflection.jl
- test/gcn.jl
```
julia> using CUDA
[ Info: Precompiling CUDA [052768ef-5323-5732-b1bb-66c8b64840ba]
julia> a = CuArray([1 2 3])
1×3 CuArray{Int64,2,Nothing}:
1  2  3
julia> @device_code_ptx a .= 5
// PTX CompilerJob of kernel broadcast(CUDA.CuKernelContext, CuDeviceArray{Int64,2,CUDA.AS.Global}, Base.Broadcast.Broadcasted{Nothing,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},typeof(identity),Tuple{Int64}}) for sm_75
//
// Generated by LLVM NVPTX Back-End
//
.version 6.3
.target sm_75
.address_size 64
// .globl       _Z15julia_broadcast15CuKernelContext13CuDeviceArrayI5Int64Li2E6GlobalE11BroadcastedIv5TupleI5OneToI5Int64E5OneToI5Int64EE9_identity5TupleI5Int64EE // -- Begin function _Z15julia_broadcast15CuKernelContext13CuDeviceArrayI5Int64Li2E6GlobalE11BroadcastedIv5TupleI5OneToI5Int64E5OneToI5Int64EE9_ide …
```
> Add support for dump_module to code_native.

- Manifest.toml
- Project.toml
- src/debug.jl
- src/driver.jl
- src/mcgen.jl
- src/optim.jl
- src/reflection.jl
- src/utils.jl
- src/validation.jl
https://github.com/maleadt/LLVM.jl/pull/194
> Adapt to LLVM.jl clean-up.

- src/cache.jl
Before:
```
ZeKernel at /home/tim/Julia/pkg/oneAPI/lib/level-zero/module.jl:78
get at /home/tim/Julia/pkg/oneAPI/lib/level-zero/module.jl:122
getindex at ./abstractdict.jl:490
unknown function (ip: 0x7f2fc638c7f5)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#_compile#32 at /home/tim/Julia/pkg/oneAPI/src/compiler/execution.jl:127
_compile at /home/tim/Julia/pkg/oneAPI/src/compiler/execution.jl:119 [inlined]
#100 at /home/tim/Julia/pkg/GPUCompiler/src/cache.jl:21 [inlined]
get! at ./dict.jl:450
macro expansion at ./lock.jl:183 [inlined]
#check_cache#99 at /home/tim/Julia/pkg/GPUCompiler/src/cache.jl:19
unknown function (ip: 0x7f2fc634d829)
_jl_invoke at …
```
> Fix compilecache CI lineinfo to improve backtraces

- .gitlab-ci.yml
- .travis.yml
- Project.toml
- test/runtests.jl
GCN seems broken:
```
error: <unknown>:0:0: in function julia__704_kernel_18579 void (float, i64): unsupported initializer for address space
```
Since we didn't ever run CI for GCN (GPUCompiler was 1.4+, while the GCN tests checked for <1.4), I've disabled the tests.
> Reinstate Julia 1.3 support.

- src/irgen.jl
`llvm.julia.gc_preserve_begin` etc
> Don't rename unofficial LLVM intrinsics.

- src/driver.jl
- src/interface.jl
- src/irgen.jl
- src/ptx.jl
- src/reflection.jl
- src/spirv.jl
- src/validation.jl
Don't emit `byval` if we'll do custom wrapping using an inner function, because leaving the `byval` on the inner function breaks the following:
```llvm
define void @outer({ i32 } addrspace(11)* %arg) {
call void @inner({ i32 } addrspace(11)* %arg)
ret void
}
define void @inner({ i32 } addrspace(11)* byval %arg) #0 {
%tmp = getelementptr { i32 }, { i32 } addrspace(11)* %arg, i32 0, i32 0
ret void
}
attributes #0 = { alwaysinline }
```
```
$ opt -verify reduce.ll -o /dev/null
$ opt -always-inline -verify reduce.ll -o /dev/null
GEP address space doesn't match type
%tmp.i = getelementptr { i32 }, { i32 }* %arg1, i32 0, i32 0
in function outer
LLVM ERROR: Broken function found, compilation aborted!
```
This only happens with struct gep (i.e. `{ i32 }` and not `i32`), so looks like an LLVM bug? …
> More byval work

- src/interface.jl
- src/ptx.jl
- src/spirv.jl
Not doing so ~~can~~ does make LLVM hang during optimization.
> Create structs and enums in the correct context.

- src/gcn.jl
- src/interface.jl
- src/optim.jl
- src/ptx.jl
- test/gcn.jl
Because Julia's optimization passes don't handle certain nuances of the AMDGPU target, we need to lie about our target during optimization. Afterwards (and before target-specifications optimizations are run) we switch back to the real target.
I'm hoping that this will reduce the number of assertions hit with the GCN backend, by letting Julia's optimization passes work on IR that is closer to what they were designed for. We can easily fixup things that deviate from the target's expectations later (such as alloca addrspaces) since we get more pass-friendly code after Julia optim.
> [GCN] Fake target early, rewrite allocas later

- src/interface.jl
- test/native.jl
Will add a test before merging. Motivation is to allow
```
struct MyCallable end
(::MyCallable)(a, b) = a+b
const mycallable = MyCallable()
FunctionSpec(mycallable, Tuple{Int, Int}, false, nothing)
```
> Allow callable structs in FSpec

- src/ptx.jl
- test/ptx.jl
Works around https://github.com/JuliaGPU/GPUCompiler.jl/issues/92.
> Lower byval ourselves for PTX.

- src/driver.jl
- src/optim.jl
- src/ptx.jl
These frequently occur from exception messages. Merge them after linking the runtime, and when doing deferred codegen.
e.g. before
```llvm
@0 = internal unnamed_addr constant [75 x i8] c"ERROR: a CUDA error was thrown during kernel execution: %s (code %ld, %s)\0A\00", align 1
@__dynamic_shmem_617 = external addrspace(3) global [0 x i64], align 32
@__dynamic_shmem_618 = external addrspace(3) global [0 x float], align 32
@exception17 = private unnamed_addr constant [10 x i8] c"exception\00", align 1
@exception42 = private unnamed_addr constant [13 x i8] c"InexactError\00", align 1
@1 = internal unnamed_addr constant [108 x i8] c"ERROR: a %s was thrown during kernel execution.\0A       Run Julia on debug level 2 for device stack traces.\0A\00", align 1
@2 = internal unnamed_addr constant …
```
> Clean-up identical constants.

- src/driver.jl
- src/irgen.jl
In https://github.com/JuliaGPU/CUDA.jl/pull/552 I noticed that the purposefully-exported constant memory symbol was getting internalized, in part because of GPUCompiler (and in part because of Julia itself). This is one part of the fix to that.
> Don't internalize global variables.

- src/cache.jl
- src/interface.jl
This is more accurate, as the compiler params can change (e.g. with or without debug info). Furthermore, it allows GPUCompiler to manage the compilation hook, which simplifies things downstream.
cc @jpsamaroo, as this is a breaking change.
> Key the compilation cache on the job, not the source

- Manifest.toml
- Project.toml
- src/GPUCompiler.jl
- src/driver.jl
- src/spirv.jl
- src/utils.jl
Rebase of https://github.com/JuliaGPU/GPUCompiler.jl/pull/120. Didn't like the whitespace change so made it a macro.
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/21.
> Lock codegen for multithreaded compilation.

- src/driver.jl
I've been triggering https://github.com/JuliaLang/julia/blob/a7848a28e5d450dcc48ef99320d3220618dba501/src/aotcompile.cpp#L264-L266, `Refusing to automatically run type inference with custom cache lookup.`, which looks like a race on the CI cache.
> Take compiler lock during inference.

- src/cache.jl
- src/rtlib.jl
Otherwise each task started doing tens of compilation jobs that all trampled over one another, ballooning the time to compile by a factor of `nthreads`.
> Make sure the runtime is generated only on one task.

- src/interface.jl
- src/irgen.jl
- src/jlgen.jl
- src/reflection.jl
- src/rtlib.jl
- src/runtime.jl
- src/validation.jl
- test/gcn.jl
- test/native.jl
- test/ptx.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/112.
Experimentation here and in #122 has shown that an overlay table is the way to go, as spoofing the codeinstance cache is unreliable (https://github.com/JuliaGPU/GPUCompiler.jl/pull/151#issuecomment-791313921). At the same time, we can't be returning a different function when replacing method lookup in the table, doing so thoroughly confuses the compiler (https://github.com/JuliaGPU/GPUCompiler.jl/pull/122#issue-529571645). So we need to keep the function type the same, but somehow convince Julia to select a different method. On 1.7, we can use a different method table for that, and use a method table view during inference that first consults the external table before querying the internal one. On 1.6, we don't have that …
> Method overrides for Julia 1.6 and 1.7.

- src/cache.jl
So that we can use things like [LRUCache.jl](https://github.com/JuliaCollections/LRUCache.jl) to back the cache.
> Allow cache to be <:AbstractDict

- src/driver.jl
- test/definitions/native.jl
- test/native.jl
This is rather funky, but it enables Enzyme to inject a full CompilerJob into the deferred_codegen_jobs,
which is needed to do higher-order adjoints and potentially running Enzyme within a CUDA kernel. 
x-ref: https://github.com/wsmoses/Enzyme.jl/pull/54
> Drive deferred codegen with CompilerJob

- src/ptx.jl
If we just pick a CPU, it selects a default subtarget feature. We need more control.
> Put the PTX ISA in the CompilerTarget.

- src/interface.jl
- src/jlgen.jl
I'd like to re-use the `jlgen` hooks for compiling method instances -- but I'd like to parametrize the pipeline with my own interpreter. I think this might be generally useful, if downstream compiler creators would like to customize Julia's type inference but still use the relatively generic caching `Core.Compiler` overloads and pipeline.
> Parametrize jlgen with custom interpreters.

- src/interface.jl
- src/jlgen.jl
- src/ptx.jl
We can now control the `debuginfo` argument from CUDA.jl, so don't need a hack here.
> Remove PTX debuginfo hack.

- Manifest.toml
- Project.toml
- src/irgen.jl
Otherwise LLVM segfaults when printing debug info for these functions.
Requires https://github.com/maleadt/LLVM.jl/pull/227.
> Copy the DI SubProgram when wrapping for ByVal.

- src/irgen.jl
- test/native.jl
Now that we have contextual overrides, we don't need to match Julia-level functions anymore. We still need to override calls to the runtime, as we can't contextually override intrinsics like `throw`. Also, for now we still need the hack that removes arguments to those runtime functions because many exception objects (like `InexactError`) have `@nospecialize` constructors (we could define overrides for all these constructors, but I'm hoping we can do that automatically with 1.7's method table overrides, or by introducing another codegen hook).
This is obviously a breaking change.
> Remove matching of Julia throw functions.

- src/driver.jl
- src/mcgen.jl
- src/spirv.jl
- src/validation.jl
- test/native.jl
Since https://github.com/JuliaGPU/GPUCompiler.jl/pull/196 was breaking, here's some more breaking changes:
- make each `emit_` method return a `meta::NamedTuple` for extensibility (so that we can at least return additional values without breaking the interface)
- remove the redundant `world` arguments -- this is part of the FunctionSpec now
- remove the undefined functions/globals metadata (cc @jpsamaroo), these are very easy to reconstruct from the outputs of `emit_llvm`. Note that back when this was introduced, it wasn't possible to call `emit_llvm` separately; the driver has since been split up.
> Breaking changes

- examples/kernel.jl
- src/cache.jl
Fewer global state modifications from generated functions is always nice.
@vchuravy See the comment, maybe you know how to get the world bounds where a code info is valid?
> Use the code info's objectid for specialization.

- src/cache.jl
This reverts commit 1b1e01588e33a3905a5b3dba2b4e1b5f4ccf8629.
As encountered with CUDA.jl's WMMA tests, two separate instances of a kernel (`@eval`ed, with interpolated constants for the layouts, so really different instances) ending up with the same `objectid`:
```
specialization_id(job) = 0x10b341ceae95481b
MUL: A: RowMajor, B: ColMajor, C: ColMajor, D: RowMajor, C type: Float32, D type: Float32: Test Passed
specialization_id(job) = 0x10b341ceae95481b
MAC: A: ColMajor, B: ColMajor, C: RowMajor, D: RowMajor, C type: Float32, D type: Float32: Test Failed at /home/tim/Julia/pkg/CUDA/wip.jl:60
```
cc @vchuravy
> Revert "Use the code info's objectid for specialization."

- src/interface.jl
- src/ptx.jl
Objectid hash is apparently expensive (100ns), but also wrong, since we want to hit the cache on identical compilation requests.
> Hash structures by fields.

- src/ptx.jl
So that we can query it at run time.
> Emit CUDA version info in the LLVM module.

- src/interface.jl
- src/spirv.jl
The BitcodeWriter on LLVM 12 assumes that `byval` has its type set, e.g., https://github.com/llvm/llvm-project/blob/77ebfba68b9aa89e9ccbcdf8e285afa0661c8ca4/llvm/lib/Bitcode/Writer/ValueEnumerator.cpp#L1068-L1069 otherwise results in a nullpointer assertion / segfault:
```
julia: /home/tim/Julia/src/julia/deps/srccache/llvm-12.0.0/include/llvm/Support/Casting.h:104: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = llvm::StructType; From = llvm::Type]: Assertion `Val && "isa<> used on a null pointer"' failed.
signal (6): Aborted
in expression starting at /home/tim/Julia/pkg/GPUCompiler/wip.jl:19
gsignal at /usr/lib/libc.so.6 (unknown line)
abort at /usr/lib/libc.so.6 (unknown line)
__assert_fail_base.cold at /usr/lib/libc.so.6 (unknown line)
__assert_fail at …
```
> Use byval with type on LLVM 12.

- src/interface.jl
- src/optim.jl
- src/spirv.jl
This PR contains 1.7-related fixes for the SPIR-V backend, which includes maintaining our own optimization pipeline so that we can disable the SLP vectorizer (which generates code that the SPIR-V toolchain doesn't support, but generally also isn't very useful for scalar GPU code). The pipeline is copied over from Enzyme.jl, but with some changes to get us back at performance parity (cc @vchuravy, the VolumeRHS integration test from CUDA.jl showed significant additional register pressure).
> More fixes for the SPIRV compiler

- src/driver.jl
This is a new API in LLVM 4.3.
> Delete function bodies instead of replacing them.

- src/jlgen.jl
https://github.com/JuliaLang/julia/pull/42149 has deleted an `OptimizationParam` we were using.
> 1.8 compatibility.

- src/runtime.jl
The former triggers a depwarn, which is a Bad Thing in generated functions.
> Use at-inline instead of _inline_meta.

- .buildkite/pipeline.yml
Enzyme.jl makes heavy use of the GPUCompiler infrastructure
and it would be helpful for us to make sure that changes in
GPUCompiler don't break Enzyme.jl unexpectedly.
Both I and @wsmoses are happy to help maintenance.
> Add Enzyme.jl to the reverse testing

- src/driver.jl
- src/gcn.jl
- test/native.jl
- test/util.jl
Without it, the manual byval lowering generates really slow code, so this PR fixes a huge regression in CUDA.jl after https://github.com/JuliaGPU/GPUCompiler.jl/pull/236.
There's something wrong with the native LazyCodegen tests though. The deferred kernel isn't in the module anymore:
```julia
julia> using Test, GPUCompiler
julia> include("test/definitions/native.jl")
julia> import .LazyCodegen: call_delayed
julia> global flag = Ref(false) # otherwise f is a closure and we can't
Base.RefValue{Bool}(false)
julia> # pass it to `Val`...
f() = (flag[]=true; nothing)
f (generic function with 1 method)
julia> function caller()
call_delayed(f)
end
caller (generic function with 1 method)
julia> @test caller() === nothing
Test Passed
Expression: caller() === nothing
Evaluated: nothing === nothing …
```
> Perform late optimization, after deferred codegen and byval lowering.

- src/driver.jl
- src/interface.jl
- src/irgen.jl
- src/optim.jl
- src/rtlib.jl
- src/runtime.jl
- test/definitions/ptx.jl
- test/ptx.jl
Turns out there were a bunch of issues with a couple of my recent PRs.
---
When we `ccall` a function that we may later link (i.e. it's a real definition, not just a declaration) we might end up with IR that relies on a bitcast:
```llvm
call void bitcast (void (double, double*, double*)* @__nv_sincos.stateless to void (double, i64, i64)*)(double %78, i64 %74, i64 %77) [ "jl_roots"({} addrspace(10)* %70, {} addrspace(10)* %65, double addrspace(11)* %8) ]
```
These weren't rewritten properly.
---
With late optimization, we're lowering calls to `julia.gc_pool_alloc` after the kernel state argument has been added. We need to take that into account, and manually add the kernel state argument. It's not easy to access that argument though, since the `julia.gpu.kernel_state_getter` intrinsic has …
> Fixes for late optimization of kernel state arguments

- Manifest.toml
- src/gcn.jl
- src/irgen.jl
- src/optim.jl
- src/rtlib.jl
- src/runtime.jl
- src/validation.jl
- test/definitions/ptx.jl
- test/ptx.jl
LLVM/NVPTX doesn't like how we pass the kernel state object by reference, and marking it `readonly byval` doesn't currently help. Awaiting better fixes, let's just pass the object by value right now.
> More kernel state optimizations

- src/runtime.jl
Ref https://github.com/JuliaLang/julia/pull/42151
> Adapt to Julia 1.8.

- src/reflection.jl
Otherwise there's no highlighting in Jupyter.
> Use color for all IO's, if supported.

- src/reflection.jl
Requires https://github.com/JuliaDebug/Cthulhu.jl/pull/242, but makes `@device_code_warntype interactive=true` work again.
> Pass the native interpreter to Cthulhu.

- Manifest.toml
- Project.toml
- src/optim.jl
- src/ptx.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/256, and adds a pass that deals with the regression from https://github.com/JuliaGPU/GemmKernels.jl/pull/83 as noted in https://github.com/JuliaGPU/GemmKernels.jl/pull/85.
Depends on https://github.com/maleadt/LLVM.jl/pull/272.
cc @thomasfaingnaert @vchuravy
> Add additional optimization passes.

- src/driver.jl
We don't emit device function slots anymore.
> Remove PTX-specific hack.

- Manifest.toml
- src/cache.jl
In order to handle callsite inlining correctly, now Julia's native
optimizer and verifier expects `src.ssaflags` to have the same length
as `src.code`.
> fix verifier warnings

- src/irgen.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/284
> Don't have LLVM clone metadata when cloning functions.

- src/ptx.jl
```julia
sin.(CuArray([1]))
```
Before:
```llvm
; PTX CompilerJob of kernel broadcast_kernel(CUDA.CuKernelContext, CuDeviceVector{Float64, 1}, Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}}, typeof(sin), Tuple{Base.Broadcast.Extruded{CuDeviceVector{Int64, 1}, Tuple{Bool}, Tuple{Int64}}}}, Int64) for sm_75
define ptx_kernel void @_Z27julia_broadcast_kernel_778315CuKernelContext13CuDeviceArrayI7Float64Li1ELi1EE11BroadcastedIv5TupleI5OneToI5Int64EE4_sinS3_I8ExtrudedIS0_IS5_Li1ELi1EES3_I4BoolES3_IS5_EEEES5_([1 x i64] %state, { i8 addrspace(1)*, i64, [1 x i64], i64 } %0, { [1 x { { i8 addrspace(1)*, i64, [1 x i64], i64 }, [1 x i8], [1 x i64] }], [1 x [1 x i64]] } %1, i64 signext %2) local_unnamed_addr #4 {
entry:
%q.i.i = alloca i32, align 4
%q.i.i.i = alloca i32, align 4 …
```
> Implement NVVMReflect in Julia.

- src/driver.jl
- src/optim.jl
These intrinsics probably will get lowered to a call to the runtime library.
> Link the runtime when specific intrinsics occur.

- src/reflection.jl
- src/validation.jl
When a GPU kernel is behind some pre-processing code on the host, it's rather cumbersome to use introspection tools on the device code. But, since `InvalidIRError` includes a `CompilerJob`, I can simply call `GPUCompiler.code_typed(err.job)` if I catch `InvalidIRError` as `err`. I like this workflow since I can rapidly iterate over my code to make it compilable.
This PR implements thin wrappers of `GPUCompiler.code_typed(err.job)` etc. as `Interactive.code_typed(err::InvalidIRError)` etc.. I think it's nice to make it easily invokable by extending `InteractiveUtils.code_typed` since users typically don't have GPUCompiler as a direct dependency (and then importing GPUCompiler is a bit tricky; e.g., `using CUDA.GPUCompiler`). Furthermore, I think it's nice to "advertise" that the exception …
> Add `code_typed(::InvalidIRError)` etc.

- src/jlgen.jl
Apologize for the confusion!
In <https://github.com/JuliaLang/julia/pull/44240>, we figured out that
`CachedMethodTable` doesn't give us any performance benefit (both in
time and space), and so we removed that from Julia Base.
This commit updates the (newly updated) GPUCompiler's overloads accordingly.
> remove `CachedMethodTable`

- src/rtlib.jl
Now that we link the runtime early, avoid optimizing it twice (https://github.com/JuliaGPU/GPUCompiler.jl/commit/6e4cfc9270275584c62a57e2cbd385988e79a408 didn't do much to actually allow re-optimization, and it's wrong, see the comment I added to the code).
> Don't optimize the runtime library.

- src/optim.jl
- src/validation.jl
- test/native.jl
- test/util.jl
@vchuravy a LazyCodegen tests fails, where you test for 'ABI removal'. I'm not sure what's up there, could you have a look?
The generated code is:
```
julia> native_code_llvm(call_real, Tuple{ComplexF64})
;  @ REPL[20]:1 within `call_real`
; Function Attrs: alwaysinline
define double @julia_call_real_3776([2 x double]* nocapture nonnull readonly align 8 dereferenceable(16) %0) local_unnamed_addr #0 {
top:
%1 = alloca [2 x double], align 16
%.sub = bitcast [2 x double]* %1 to i8*
call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %.sub)
;  @ REPL[20]:2 within `call_real`
; ┌ @ /home/tim/Julia/pkg/GPUCompiler/test/definitions/native.jl:309 within `call_delayed`
; │┌ @ /home/tim/Julia/pkg/GPUCompiler/test/definitions/native.jl:243 within `abi_call`
; ││┌ @ …
```
> Fixes for 1.8

- src/jlgen.jl
JuliaLang/julia#44389 removed `method_table(::AbstractInterpreter, ::InferenceState)` interface,
and now we should overload `method_table(::AbstractInterpreter)` instead.
> update to JuliaLang/julia#44389

- test/native.jl
Also marks the test from https://github.com/JuliaGPU/GPUCompiler.jl/issues/307 broken for now.
> Use at-test_broken to denote broken tests.

- Project.toml
- src/driver.jl
- src/interface.jl
- src/native.jl
- src/optim.jl
- test/definitions/native.jl
- test/native.jl
As noted in https://github.com/EnzymeAD/Enzyme.jl/pull/243
The issue is that for nested Codegen Enzyme uses the NativeCompilerTarget or PTXCompilerTarget 
and so it picks up the default for each.
> NativeCompilerTarget should support throwing

- src/driver.jl
- src/interface.jl
- src/irgen.jl
- src/reflection.jl
- test/definitions/native.jl
- test/native.jl
Useful for CPU compilation where we don't want to figure out the ABI manually
> Support func entry

- src/jlgen.jl
- src/validation.jl
- test/native.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/309
Still we want to wait for the release of [next beta version](https://github.com/JuliaLang/julia/pull/44324) and change the version compat accordingly.
> Adapt to upstream changes to return_types

- src/irgen.jl
- src/ptx.jl
- src/spirv.jl
Avoid using a materializer by setting the functions in the value map.
This in turn results in IR metadata being properly patched up automatically.
> Simplify IR cloning.

- src/irgen.jl
By putting the function in the VMap, constants are rewritten properly.
> Don't drop constants while cloning IR.

- src/irgen.jl
- src/validation.jl
In https://github.com/JuliaGPU/CUDA.jl/issues/1482, where GPUCompiler is invoked with a bunch of CuArray code (i.e., a very invalid and GPU-incompatible compilation job), the kernel state rewriting pass failed. Turns out we weren't properly supporting several IR constructs Julia likes to emit, most notably constant expressions that contain references to a function (e.g., bitcasting them, or doing a ptrtoint before passing the function as a pointer).
This PR fixes that, supporting the above use case (which still fails, but at least doesn't crash the compiler now). There's two remaining issues:
- `jlcall`, which pass an array of arguments: we don't rewrite those, which would require allocating a new array of arguments (with the kernel state prepended). shouldn't matter for now, as only the …
> Kernel state rewriting: support more IR

- Manifest.toml
- Project.toml
- src/driver.jl
- src/interface.jl
- src/irgen.jl
- src/optim.jl
- src/ptx.jl
- src/rtlib.jl
- src/runtime.jl
- src/spirv.jl
> Perform all kernel-state transformations late

- src/interface.jl
- src/irgen.jl
Small pieces of functionality that will be needed.
@vchuravy thoughts on the `meta` field in CompilerJob? Returning all kinds of metadata from functions like `emit_llvm` is cumbersome (I specifically have to escape some info from `finish_module!` which currently doesn't return a value). Maybe we should then also encode the metadata returned from `emit_llvm` in this dictionary?
> Changes in preparation of adding Metal support

- Manifest.toml
- Project.toml
- src/driver.jl
- src/gcn.jl
- src/irgen.jl
- src/mcgen.jl
- src/optim.jl
- src/ptx.jl
- src/reflection.jl
- src/rtlib.jl
- src/runtime.jl
- src/spirv.jl
Greatly improves performance by avoiding closures. See https://github.com/maleadt/LLVM.jl/pull/309 for details.
> Use at-dispose from LLVM.jl.

- .buildkite/pipeline.yml
- .github/workflows/ci.yml
- src/driver.jl
- src/interface.jl
- src/irgen.jl
- src/jlgen.jl
- src/precompile.jl
- src/reflection.jl
- src/rtlib.jl
- test/definitions/native.jl
From changes originally by @collinwarner
> Use ThreadSafeModule/Context on Julia 1.9

- src/metal.jl
- test/metal.jl
Turns out that using module cloning isn't working here. If we change
the address space of the arguments, and just remap those arguments
using a value mapper, those changes will get lost after, e.g., a
bitcast from the argument pointer to a different type (that destination
type won't have an address space, resulting in invalid operations).
We were working around this limitation by using a type remapper,
rewriting all pointer types to contain an address space, but that's
obviously invalid: Stack space (i.e. `alloca`s) should still reside
in address space 0.
So instead we're taking the approach we're using with byval lowering,
storing the arguments to a temporary slot. We're still changing the
function's pointer arguments to include an address space, but after
loading the argument and …
> Metal: Change approach to adding ptr arg ASs.

- .buildkite/pipeline.yml
- src/interface.jl
- src/irgen.jl
- src/metal.jl
Latest version of the Metal API greatly simplifies argument passing -- no complicated metadata required anymore -- so let's get rid of most of the code supporting that.
> Metal simplifications

- src/interface.jl
- src/jlgen.jl
- src/ptx.jl
- src/validation.jl
- test/definitions/ptx.jl
- test/ptx.jl
Add the ability for backends to define their own inference and optimization parameters.  This is used to add the `always_inline` target property the to ptx backend enabling the forced inlining of functions.  These changes build on the code and suggestions given in https://github.com/JuliaGPU/GPUCompiler.jl/pull/186.
> Add `always_inline` target property to ptx backend

- src/validation.jl
@claforte indicated that the `Reason` text is easy to miss in the noise, and also that it's not immediately clear that Cthulhu.jl is necessary for interactive reflection. Of course, trying to do `code_typed(err; interactive=true)` will throw an appropriate error if Cthulhu is not available, but it seems that it might be helpful to point that out earlier rather than later.
> Slightly improve validation error message

- .github/workflows/ci.yml
- src/utils.jl
> Disable checksum verification during Julia build.

- src/irgen.jl
- src/ptx.jl
- src/utils.jl
This should help Enzyme to not assume that this assembly has
any effects it needs to handle.
> Annotate exit/trap with noreturn & inaccessiblememonly

- src/jlgen.jl
MIs are considered unique by pointer-identity. So use an IdDict here since that will allow for serialization and de-serialization.
cc: @collinwarner
> MethodInstances are unique so we can use an IdDict here.

- src/jlgen.jl
> irgen: Disable fn entry safepoints

- src/interface.jl
- src/jlgen.jl
- test/definitions/native.jl
- test/native.jl
- test/util.jl
https://github.com/JuliaGPU/GPUCompiler.jl/pull/365#discussion_r1010531721
@vchuravy
> interface: Make entry safepoint emission controllable

- src/interface.jl
- src/metal.jl
- src/native.jl
- src/ptx.jl
- test/definitions/bpf.jl
- test/definitions/gcn.jl
- test/definitions/metal.jl
- test/definitions/native.jl
- test/definitions/ptx.jl
- test/definitions/spirv.jl
- test/gcn.jl
- test/native.jl
- test/ptx.jl
@maleadt remind me should we put `always_inline` into `runtime_slug`?
I also noticed that `PTXCompilerTarget` implements `hash`, but `GCNCompilerTarget` doesn't.
> Implement always_inline as a CompilerJob property

- src/driver.jl
- src/native.jl
- test/definitions/native.jl
- test/gcn.jl
Otherwise the `kernel` example fails on macOS running Julia 1.9:
```
Reason: unsupported call through a literal pointer (call to pthread_getspecific)
```
This is because the TLS getter is lowered differently:
```llvm
define void @_Z17julia_kernel_2628() #0 !dbg !4 {
top:
%0 = call {}*** @julia.get_pgcstack()
%1 = bitcast {}*** %0 to {}**
%current_task = getelementptr inbounds {}*, {}** %1, i64 -13
%2 = bitcast {}** %current_task to i64*
%world_age = getelementptr inbounds i64, i64* %2, i64 14
%3 = bitcast {}*** %0 to {}**
%current_task1 = getelementptr inbounds {}*, {}** %3, i64 -13
%ptls_field = getelementptr inbounds {}*, {}** %current_task1, i64 15
%ptls_load = load {}*, {}** %ptls_field, align 8, !tbaa !7
%ptls = bitcast {}* %ptls_load to {}**
fence syncscope("singlethread") seq_cst …
```
> Have the default target default to not using the Julia runtime.

- src/GPUCompiler.jl
- src/driver.jl
- src/irgen.jl
- src/utils.jl
- test/metal.jl
- test/runtests.jl
While looking at #374 I was curious if I could reproduce the issue in the GPUCompiler testsuite.
The answer is yes, with the change here and `CI=true julia -g2` 
```
kernel argument attributes: Error During Test at /home/vchuravy/src/GPUCompiler/test/ptx.jl:20
Got exception outside of a @test
LLVM error: mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
call void @llvm.dbg.declare(metadata [1 x i64]* undef, metadata !18, metadata !DIExpression(DW_OP_deref)), !dbg !22
label %conversion
void ([1 x i64], [1 x i64])* @_Z17julia_kernel_62489Aggregate
!18 = !DILocalVariable(name: "x", arg: 2, scope: !19, file: !3, line: 21, type: !12)
!19 = distinct !DISubprogram(name: "kernel", linkageName: "julia_kernel_6248", scope: null, file: !3, line: 21, type: !8, scopeLine: 21, …
```
> Make verify on CI by default

- src/jlgen.jl
- test/native.jl
This was reverted in https://github.com/JuliaLang/julia/pull/47602, but is still live on master. cc @vchuravy
> Don't use safepoint_on_entry cgparam on 1.9-beta1 and up.

- src/reflection.jl
So that we can use Cthulhu to debug kernels which always throw (return `Union{}`).
> Support interactive reflection for KernelError

- src/jlgen.jl
Avoids the following warning:
```
warning: linking module flags 'Dwarf Version': IDs have conflicting values ('i32 4' from globals with 'i64 4' from start)
```
... although I'm not sure where the linking happens, as we're now responsible for configuring the module. Maybe this comes from `libdevice`. Either way, doesn't hurt to fix.
> Emit 'Dwarf Version' metadata as Int32.

- src/irgen.jl
- src/ptx.jl
- src/utils.jl
This reverts commit 01d44c368d4db8fea81e31234a9085e7ea837e69.
Seems to be causing miss-compilations in Oceananigans.jl on Pascal generation GPUs.
Waiting for https://github.com/CliMA/Oceananigans.jl/pull/2906 to fully confirm, but the tests are already further...
cc: @wsmoses
> Revert "Annotate exception handling with call site effects (#359)"

- src/driver.jl
- src/rtlib.jl
- test/native.jl
Metal's LLVM post-processing inspects arguments (as does CUDA.jl's), so we need to make sure there's no invalid stuff in there. Currently, we were only running the code instance validation during `emit_asm`, instead make it happen as early as possible, during `emit_julia`.
```
Got exception outside of a @test
LoadError: Type Array does not have a definite size.
Stacktrace:
[1] sizeof(x::Type)
@ Base ./essentials.jl:473
[2] add_argument_metadata!(job::GPUCompiler.CompilerJob, mod::LLVM.Module, entry::LLVM.Function)
@ GPUCompiler ~/Julia/pkg/GPUCompiler/src/metal.jl:612
[3] finish_ir!(job::GPUCompiler.CompilerJob{GPUCompiler.MetalCompilerTarget}, mod::LLVM.Module, entry::LLVM.Function)
@ GPUCompiler ~/Julia/pkg/GPUCompiler/src/metal.jl:108
[4] macro expansion
@ …
```
> Validate inputs and outputs earlier.

- test/native.jl
This was changed in https://github.com/JuliaDebug/Cthulhu.jl/pull/356
> Fix test suite after Cthulhu.jl update.

- examples/kernel.jl
- src/bpf.jl
- src/cache.jl
- src/driver.jl
- src/error.jl
- src/gcn.jl
- src/interface.jl
- src/irgen.jl
- src/jlgen.jl
- src/mcgen.jl
- src/metal.jl
- src/native.jl
- src/optim.jl
- src/ptx.jl
- src/reflection.jl
- src/rtlib.jl
- src/spirv.jl
- src/validation.jl
- test/definitions/bpf.jl
- test/definitions/gcn.jl
- test/definitions/metal.jl
- test/definitions/native.jl
- test/definitions/ptx.jl
- test/definitions/spirv.jl
- test/native.jl
Currently, we need to re-create the entire `CompilerJob` struct every time we want to check the cache because it contains the function we want to compile. For example, simplified from https://github.com/JuliaGPU/CUDA.jl/blob/dbcaca84191fb8621f097d85dad80e1627f1c11b/src/compiler/execution.jl#L299-L308:
```julia
function compile(ft::F, tt::TT) where {F,TT}
function compiler(job)
GPUCompiler.compile(:asm, job)[1]
end
function linker(job, compiled)
compiled
end
source = FunctionSpec(ft, tt)
target = NativeCompilerTarget()
params = TestCompilerParams()
job = CompilerJob(source, target, params)
GPUCompiler.cached_compilation(cache, job, compiler, linker)::String
end
```
This results in unnecessary allocations on every kernel launch, even if it didn't cause any compilation:
```
julia> @benchmark …
```
> Split CompilerJob in dynamic and static part.

- .github/workflows/ci.yml
- test/definitions/native.jl
- test/native.jl
- test/testhelpers.jl
Counterpart of https://github.com/JuliaLang/julia/pull/48988.
Will be broken until backports-release-1.9 is merged into release-1.9 (to include https://github.com/JuliaLang/julia/commit/a82477b0c39556e0f771e38c563e069704ec65d3).
> Add a test for kwcall with overlays.

- examples/kernel.jl
- src/cache.jl
- src/driver.jl
- src/interface.jl
- src/irgen.jl
- src/rtlib.jl
- test/definitions/bpf.jl
- test/definitions/gcn.jl
- test/definitions/metal.jl
- test/definitions/native.jl
- test/definitions/ptx.jl
- test/definitions/spirv.jl
I had switched the CompilerJob args around in https://github.com/JuliaGPU/GPUCompiler.jl/pull/394 to ensure we spot erroneous uses, but https://github.com/JuliaGPU/GPUCompiler.jl/pull/402 changed it in other incompatible ways, so let's switch the order back to simplify adapting to these changes.
Also adds back the `name` keyword.
> Reduce breakage

- src/driver.jl
The following MWE:
```julia
using CUDA
function hello()
@cuda dynamic=true world()
return
end
function world()
return
end
@cuda hello()
```
... resulted in an abort:
```
julia: /home/tim/Julia/src/julia/src/jitlayers.cpp:191: jl_value_t* (* _jl_compile_codeinst(jl_code_instance_t*, jl_code_info_t*, size_t, llvm::orc::ThreadSafeContext))(jl_value_t*, jl_value_t**, uint32_t, _jl_code_instance_t*): Assertion `codeinst->min_world <= world && (codeinst->max_world >= world || codeinst->max_world == 0) && "invalid world for method-instance"' failed.
[211930] signal (6.-6): Aborted
in expression starting at /home/tim/Julia/pkg/CUDA/wip.jl:20
unknown function (ip: 0x7f70892968ec)
gsignal at /usr/lib/libc.so.6 (unknown line)
abort at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: …
```
> Don't look up the method age during deferred compilation.

- Manifest.toml
- Project.toml
- src/metal.jl
Our back-end was doing this already, but for some reason the LLVM 14-based Yggdrasil build messes this up. I can't reproduce locally, so just move that operation into GPUCompiler.jl
> Metal: Set the SDK Version metadata.

- .buildkite/pipeline.yml
Enzyme.jl is currently incompatible with GPUCompiler 0.18, and because it generally takes a while for that package to catch up let's just mark installation failures as soft_fail.
> Allow reverse testing failure if installation failed.

- src/cache.jl
Adapts to https://github.com/JuliaLang/julia/pull/48611.
Helps towards https://github.com/JuliaGPU/GPUCompiler.jl/issues/146, but doesn't fix it yet.
Ref https://github.com/JuliaGPU/GPUCompiler.jl/pull/394
> Adapt handling of world ages to upstream changes

- examples/kernel.jl
- src/cache.jl
- src/driver.jl
- src/interface.jl
- src/irgen.jl
- src/jlgen.jl
- src/reflection.jl
- src/rtlib.jl
- src/validation.jl
- test/definitions/bpf.jl
- test/definitions/gcn.jl
- test/definitions/metal.jl
- test/definitions/native.jl
- test/definitions/ptx.jl
- test/definitions/spirv.jl
- test/gcn.jl
- test/metal.jl
- test/ptx.jl
- test/spirv.jl
With the `kernel` and `name` kwargs gone, `FunctionSpec` was becoming useless, so cut it out and replace it with Julia's `MethodInstance`, as suggested by @vtjnash & @vchuravy.
@jpsamaroo This is obviously breaking, but should just require changing `FunctionSpec` to `methodinstance`. In addition, I'm removing `emit_julia` since that function only served to look-up the method instance, but in a follow-up PR I'm going to change things so that you will be able to just call `GPUCompiler.compile` and won't need to call into any specific `emit_` function again.
> Replace FunctionSpec with methodinstance

- src/interface.jl
- test/definitions/native.jl
The docstring said `entry_name`, but the code used `name` as the field - this PR makes them consistently use `entry_name`.
> Fix docstring <-> code mismatch of `CompilerConfig`

- .github/workflows/ci.yml
- src/irgen.jl
This depends on #422 due to changing the same line in `irgen.jl`. 
Opening as a draft until #422 is closed.
> Drop prefix from explicitly set entrypoint 

- Project.toml
- src/irgen.jl
- src/jlgen.jl
- src/reflection.jl
- test/definitions/native.jl
`Union{}` shouldn't appear in types, but with SciML it does, so we should support it.
Also a bunch of small fixes I had locally after debugging a 1.6-related issue.
> Minor fixes

- src/utils.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/431
> Prevent invalidations of safe logging functionality by custom loggers.

- src/optim.jl
- test/native.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/437 on versions of Julia that don't have https://github.com/JuliaLang/julia/pull/49551.
> Save and restore function attributes across optimization.

- src/jlgen.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/442
> Clarify invoke backedge invalidation.

- src/execution.jl
Generators and closures in there causes unnecessary recompilation during at-cuda lowering.
> Optimize the execution macro helper functionality.

- Project.toml
- src/metal.jl
- test/definitions/metal.jl
- adds a device-side version getter for the Metal and AIR version, while making both configurable
- adds function attributes for some intrinsics
We were also always using Metal 2.4.0, even on macOS 13 (while using Metal 3-only features)... Not sure why that did work. I'm also not sure what the difference is between the Metal and AIR version; we emit the same version for both.
> Improvements for Metal

- src/gcn.jl
- src/interface.jl
- src/irgen.jl
- src/metal.jl
- src/native.jl
- src/ptx.jl
- src/spirv.jl
- src/validation.jl
The 'extension points' had grown to quite a couple: `process_module`, `process_entry`, `link_libraries`, `finish_module`, `optimize_module`, `finish_ir` and `validate_module`. I propose we remove the first two, as they can just be implemented as part of `finish_module` (I don't think there should be a semantic difference).
Added deprecations to avoid yet another version bump.
> Simplify interfaces

- src/precompile.jl
- src/ptx.jl
During back-end compilation, `ptxas` inserts instructions to manage the harware's reconvergence stack (SSY and SYNC). In order to do so, it needs to identify
divergent regions:
```
entry:
// start of divergent region
@%p0 bra cont;
...
bra.uni cont;
cont:
// end of divergent region
bar.sync 0;
```
Meanwhile, LLVM's branch-folder and block-placement MIR passes will try to optimize the block layout, e.g., by placing unlikely blocks at the end of the function:
```
entry:
// start of divergent region
@%p0 bra cont;
@%p1 bra unlikely;
bra.uni cont;
cont:
// end of divergent region
bar.sync 0;
unlikely:
bra.uni cont;
```
That is not a problem as long as the unlikely block continunes back into the divergent region. Crucially, this is not the case with unreachable control flow:
```
entry:
// …
```
> PTX: Lower unreachable control flow to avoid bad CFG reconstruction

- src/GPUCompiler.jl
> Define compile_cache outside __init__()

- src/jlgen.jl
Closes https://github.com/JuliaGPU/GPUCompiler.jl/issues/472.
> Adapt to upstream changes.

- .github/workflows/ci.yml
- Manifest.toml
- Project.toml
- examples/kernel.jl
- src/driver.jl
- src/gcn.jl
- src/interface.jl
- src/irgen.jl
- src/jlgen.jl
- src/mcgen.jl
- src/metal.jl
- src/native.jl
- src/optim.jl
- src/precompile.jl
- src/ptx.jl
- src/reflection.jl
- src/rtlib.jl
- src/runtime.jl
- src/spirv.jl
- src/validation.jl
- test/bpf.jl
- test/definitions/bpf.jl
- test/definitions/gcn.jl
- test/definitions/metal.jl
- test/definitions/native.jl
- test/definitions/ptx.jl
- test/definitions/spirv.jl
- test/native.jl
ref https://github.com/maleadt/LLVM.jl/pull/358
> Adapt to LLVM.jl 6.

- Project.toml
- src/GPUCompiler.jl
While working on GemmKernels.jl, I noticed that the 1.6 tests occasionally failed with `unknown call to julia.get_pgcstack` or LLVM bitcode signature mismatches. Both seem to indicate that we're loading a runtime from a more recent version of Julia. This is possible because CI doesn't wipe scratchspaces, and we don't automatically invalidate the GPUCompiler compilecache (and we shouldn't have to). To prevent that, add the Julia and package version to the compilecache path.
> Version the compilecache.

- src/ptx.jl
I think this should all be fine, seems to work as intended for me.
> Add fastmath flag to PTXCompilerTarget

- Manifest.toml
- Project.toml
- src/GPUCompiler.jl
- src/driver.jl
- src/gcn.jl
- src/irgen.jl
- src/mcgen.jl
- src/metal.jl
- src/optim.jl
- src/ptx.jl
- src/rtlib.jl
- src/spirv.jl
Anywhere we fail to convert to NewPM/it's very tedious points to a hole in the NewPM API, so this serves to flush out remaining API issues.
Known issues:
> Use NewPM wherever possible

- src/GPUCompiler.jl
- src/irgen.jl
- src/mangling.jl
Because we're using the external codegen policy, Julia doesn't do this for us.
Closes https://github.com/JuliaLang/julia/pull/51099
> Ensure global variables have a safe name.

- src/validation.jl
Trial balloon. Currently, we eagerly disallow returns, even of `Union{}` (which indicates an error):
```
julia> @cuda threads=(10, 10) kernel(array_dev)
ERROR: GPU compilation of MethodInstance for kernel(::CuDeviceVector{Int64, 1, Int32}) failed
KernelError: kernel returns a value of type `Union{}`
Make sure your kernel function ends in `return`, `return nothing` or `nothing`.
If the returned value is of type `Union{}`, your Julia code probably throws an exception.
Inspect the code with `@device_code_warntype` for more details.
Stacktrace:
[1] check_method(job::GPUCompiler.CompilerJob)
@ GPUCompiler ~/Julia/pkg/GPUCompiler/src/validation.jl:36
[2] macro expansion
@ GPUCompiler ~/Julia/pkg/GPUCompiler/src/driver.jl:122 [inlined]
```
I'm not sure that's very user-friendly however, as it …
> Don't disallow Bottom returns.

- src/driver.jl
Another hotfix for https://github.com/JuliaGPU/GPUCompiler.jl/pull/510: Turns out the LLVM verifier can be unhappy about non-void kernels:
```
julia> invalid_kernel() = throw()
@oneapi invalid_kernel()
ERROR: LLVM error: Calling convention requires void return type
{}* ()* @_Z14invalid_kernel
Stacktrace:
[1] verify(mod::LLVM.Module)
@ LLVM ~/Julia/pkg/LLVM/src/analysis.jl:10
```
... so make sure we validated the IR ourselves first.
It's not perfect, as our reflection macros invoke the driver with `validate=false`:
```
julia> @device_code_llvm @oneapi invalid_kernel()
; GPUCompiler.CompilerJob{GPUCompiler.SPIRVCompilerTarget, oneAPI.oneAPICompilerParams}(MethodInstance for invalid_kernel(), CompilerConfig for GPUCompiler.SPIRVCompilerTarget, 0x0000000000007f13)
ERROR: LLVM error: Calling …
```
> Verify IR after our own validation.

- src/metal.jl
- test/metal_tests.jl
Julia emits these on 1.10 when doing CartesianIndices operations:
```
julia> fill!(view(MtlArray{Float32}(undef, 2, 2), 2:2, 2:2), 0)
ERROR: Unsupported intrinsic type: LLVM.VectorType(<2 x i64>)
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] lower_llvm_intrinsics!(job::GPUCompiler.CompilerJob, fun::LLVM.Function)
@ GPUCompiler ~/Julia/pkg/GPUCompiler/src/metal.jl:893
[3] finish_ir!(job::GPUCompiler.CompilerJob{GPUCompiler.MetalCompilerTarget}, mod::LLVM.Module, entry::LLVM.Function)
@ GPUCompiler ~/Julia/pkg/GPUCompiler/src/metal.jl:129
```
> Metal: Support vector-valued intrinsics.

- src/optim.jl
Although we may want some additional configurability here, let's quickly disable it now as our Legacy PM pipeline doesn't have vectorization passes, because we specifically disabled those. This results in compilation failures with Metal, but I'm sure not all GPU back-ends support arbitrary vector operations (or know how to legalize them).
> Disable the vectorizer pipeline.

- src/irgen.jl
- src/metal.jl
This seems required now on macOS Sonoma, and the compiler crashes without it.
Fixes https://github.com/JuliaGPU/Metal.jl/issues/201
> Metal: Emit name metadata.

- src/optim.jl
- src/utils.jl
```julia
julia> function main()
function kernel(a)
@loopinfo unroll for i = eachindex(a)
a[i] = 0
end
return
end
arr = CUDA.zeros(10)
@cuda kernel(arr)
end
main (generic function with 1 method)
julia> empty!(CUDA.compiler_cache(context())); main()
CUDA.HostKernel for kernel(CuDeviceVector{Float32, 1})
julia> ENV["JULIA_DEBUG"] = "GPUCompiler"
"GPUCompiler"
julia> empty!(CUDA.compiler_cache(context())); main()
warning: abstractarray.jl:699:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
CUDA.HostKernel for kernel(CuDeviceVector{Float32, 1})
```
cc @pchintalapudi
> Only warn about missed transformations when debug output is enabled.

- Project.toml
- src/precompile.jl
- src/ptx.jl
Reviewing https://github.com/llvm/llvm-project/pull/67478, I realized that we shouldn't be throwing away `trap` as eagerly as we are. Instead, we should just actively call `exit` when we expect recovery, i.e., when we're handling an exception. This will require a change in CUDA.jl.
> PTX: Improve handling of trap

- src/jlgen.jl
JuliaLang/julia#51769 allows us to not traverse backedge list by ourselves.
> use `CC.add_invalidation_callback!` if available

- src/metal.jl
- test/metal_tests.jl
Intrinsics like `@air.max.s64` don't seem to work on Intel Macs, however `@air.max.s.i64` does work.
Interestingly the `@air.max.s64` intrinsic does work on M-series chips just fine and the final AGX is the same as with `@air.max.s.i64`.
The Apple Metal compiler seems to prefer the latter intrinsic style (`@air.max.s.i64`):
```c++
#include <metal_stdlib>
using namespace metal;
kernel void add_arrays(device const long2* inA,
device const long2* inB,
device long2* result,
uint index [[thread_position_in_grid]])
{
result[index] = max(inA[index], inB[index]);
}
```
```llvm
source_filename = "add_arrays"
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:25 …
```
> Fix type suffix of integer intrinsics

- src/jlgen.jl
We should definitly look at other uses of `get_world_counter` since that will be the global max.
> Adjust for upstream JuliaLang/julia#53088

- src/jlgen.jl
GPUCompiler's `methodinstance` function is pretty slow and allocates:
```julia
julia> @benchmark GPUCompiler.methodinstance(typeof(identity), Tuple{Nothing}, GPUCompiler.tls_world_age())
BenchmarkTools.Trial: 10000 samples with 204 evaluations.
Range (min … max):  378.623 ns …  11.078 μs  ┊ GC (min … max): 0.00% … 95.51%
Time  (median):     389.853 ns               ┊ GC (median):    0.00%
Time  (mean ± σ):   401.785 ns ± 312.086 ns  ┊ GC (mean ± σ):  2.66% ±  3.28%
▂▆▇█▆▄▂▁▁▂▁▂▁
▂▂▂▂▁▂▂▂▂▂▃▄▆██████████████▇▅▄▄▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ ▄
379 ns           Histogram: frequency by time          414 ns <
Memory estimate: 288 bytes, allocs estimate: 6.
```
That's why on 1.10, we improved this by using a generated function to cache the dynamic case, automatically invalidating the result …
> Use the new jl_method_lookup_by_tt API on 1.11.

- src/jlgen.jl
@vtjnash is there a way to speedup this query? For `identity(::Int)` this currently takes ~500ns
The goal here is to compute the `mi` we would have `invoked`.
> Specialize MI if necessary

- .github/workflows/ci.yml
- .gitignore
- src/interface.jl
- src/jlgen.jl
- src/rtlib.jl
- test/Project.toml
replaces #534
adapts to JuliaLang/julia#52233
> Support internal cache

- Project.toml
- src/metal.jl
Works around the changes from https://reviews.llvm.org/D135780. I'm not sure why the IR Autoupgrader didn't kick in...
x-ref https://github.com/JuliaGPU/GPUCompiler.jl/issues/565
> Metal: Work around function attribute changes in LLVM 16.

- src/optim.jl
- test/gcn_tests.jl
- test/ptx_tests.jl
I compared Julia's native PM with the definitions here
while looking at https://github.com/JuliaGPU/CUDA.jl/issues/2313
The generated IR in the issue seems equivalent, but the
result of the optimization pipeline differs.
> Update New PassManager Pipeline

- src/driver.jl
- src/interface.jl
- src/jlgen.jl
This is convenient for some experiments I'm doing with GPU opaque closures, where we want to insert additional CIs in the cache that are not inferrable by themselves.
> Add an interface extension point to prepare before anything happens.

- src/driver.jl
- src/interface.jl
- src/optim.jl
We also need to make sure that we have an optimization mode (probably `-O1`?) that only lightly optimizes, e.g. not doing loop unrolling or unswitching, but just optimizing Julia's typical IR patterns away. This is for use with shader compilers (i.e., Metal, SPIR-V, NVVM) which do their own optimization.
> Make the optimization level configurable.

- src/GPUCompiler.jl
see: https://github.com/JuliaLang/PackageCompiler.jl/issues/896
> Fix issue with `__init__` when built in sysimg

- src/GPUCompiler.jl
Closes https://github.com/JuliaGPU/GPUCompiler.jl/issues/593
> Work around buggy Base.pkgversion again.

- src/driver.jl
- src/precompile.jl
- src/rtlib.jl
This simplifies the kwarg values used in `compile`/`codegen`, and should make a little more clear what's happening and when.
It breaks the `precompile.jl`, but with the recent work by @vchuravy I take it we better move to an actual precompilation workload anyway?
> Set codegen kwargs based on toplevel setting (NFC)

- src/rtlib.jl
- src/runtime.jl
Generates better error messages for https://github.com/JuliaGPU/GPUCompiler.jl/issues/596:
- detects the argument count mismatch (`Incorrect number of arguments for runtime function: passing 1 argument(s) to 'void () report_exception'`)
- in addition, refuses to generate an intrinsic call to a pre-defined function in the module (`Calling an intrinsic function that clashes with an existing definition: void (i64) report_exception`). This is fairly strict, but without controlling the intrinsic definition it's possible that it doesn't match the expected behavior (i.e., what probably caused #596 in the first place).
> Be more strict about runtime function misuse.

- src/GPUCompiler.jl
- src/driver.jl
- src/irgen.jl
- src/mcgen.jl
- src/metal.jl
- src/optim.jl
- src/ptx.jl
- src/rtlib.jl
Now that we only support Julia 1.10, which ships LLVM 15, we can almost entirely switch to LLVM's new pass manager.
Also fixes use of the InternalizePass for 1.12.
> Default to using NewPM.

- .buildkite/pipeline.yml
- src/gcn.jl
- src/rtlib.jl
~~- Fix issues observed in CI after 0.27 update:
https://buildkite.com/julialang/amdgpu-dot-jl/builds/2551#019128fc-5ca0-4674-bf9c-2ebc853bfad3/6-24~~
- Enable AMDGPU CI (for 1.10 and 1.11 with opaque pointers enabled).
- Remove unused GCN functionality.
> Add CI jobs for AMDGPU

- src/mangling.jl
- test/util_tests.jl
Fixes #609.
I also noticed that zeros were not being mangled correctly (the `n` prefix should only be added if the value is negative, not if equal to zero).
> fix mangling of booleans and zeros

- src/execution.jl
- src/rtlib.jl
The `force` keyword argument to `rename` was removed in https://github.com/JuliaLang/julia/pull/55384 to replace the stopgap solution added in https://github.com/JuliaLang/julia/pull/36638#discussion_r453820564 by making the regular `mv(tmppath, cachefile; force = true)` more atomic.
> Fix use of Base.rename for 1.12

- Project.toml
- src/metal.jl
`replace_unreachable!` currently doesn't handle trivial trapping functions, but `hide_noreturn!` does, so just switch the order of these two passes.
https://github.com/JuliaGPU/Metal.jl/pull/321#issuecomment-2313201384
> Metal: switch order of unreachable rewrite passes.

- src/utils.jl
- test/Project.toml
- test/util_tests.jl
GPUCompiler's safe loggers temporarily replace the global logger with a simple non-yielding logger. But this does nothing if a different current logger is set, in which case the loggers are unsafe and will error if the custom logger yields, as seen in https://github.com/fonsp/Pluto.jl/issues/3012. This PR changes the safe loggers to use `with_logger` instead of `global_logger`, to ensure that the yield-free logger is the one that's actually used.
In addition, I made it so that the safe logger inherits `Logging.shouldlog` from the current logger, not just `Logging.min_enabled_level`. The reasoning is that many loggers set `min_enabled_level` to the minimum possible value and rely on `shouldlog` for filtering; Pluto's logger is a case in point. I implemented a dedicated `SafeLogger` type to …
> Replace current, not global logger in safe loggers

- src/metal.jl
- src/validation.jl
- test/metal_tests.jl
Allow `double` for C's default argument promotions used in variable-length argument lists by introducing `ir_check_ignore` metadata and a allow argument for `check_ir_values` that is used to allow `fpext` in Metal.
needed for https://github.com/JuliaGPU/Metal.jl/pull/418
> Add exceptions to check_ir_values

- src/mangling.jl
- test/Project.toml
- test/util_tests.jl
I was finally fed up with some complex signatures not rendering nicely in the profiler, but it took a couple of hours to squash all the bugs. We can now successfully mangle the following:
```julia
julia> GPUCompiler.mangle_sig(Tuple{GPUArrays.var"#35#37", CUDA.CuKernelContext, CuDeviceMatrix{Float32, 1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2, CUDA.DeviceMemory}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(Base.literal_pow), Tuple{CUDA.CuRefValue{typeof(^)}, Base.Broadcast.Extruded{CuDeviceMatrix{Float32, 1}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}, CUDA.CuRefValue{Val{2}}}}, Int64})
"_Z3_3515CuKernelContext13CuDeviceArrayI7Float32Li2ELi1EE11BroadcastedI12CuArrayStyleILi2E12DeviceMemoryE5TupleI5OneToI5Int64ESA_E11literal_powS7_I10CuRefValueI1_E8ExtrudedIS2_S7_I4BoolSH_ES7_I …
```
> Fix and test mangling

- .github/workflows/ci.yml
- src/optim.jl
x-ref https://github.com/JuliaLang/julia/pull/55802
> Adapt to removal of CombineMulAdd pass.

- src/jlgen.jl
- test/native_tests.jl
- test/ptx_tests.jl
Relies on https://github.com/JuliaLang/julia/pull/56693
> Fixes for nightly

- src/validation.jl
- test/native_tests.jl
Since we cannot load from these, we can tolerate passing them to a GPU. This makes it possible to use symbols.
> Validator: Permit all fieldless objects.

- src/metal.jl
- test/metal_tests.jl
Global constants need to be located in address space 2 in Metal:
This fixes the following use case:
```julia
using Metal
using StaticArrays
const xs = SVector(1.0f0, 2.0f0, 3.0f0)
function kernel_fma(a, b, x, out)
i = thread_position_in_grid_1d()
a_val = a[i]
b_val = b[i]
x_val = x[i]
out[i] = fma(a_val, b_val, xs[x_val])
return
end
len=1024
a = MtlArray(rand(Float32, len))
b = MtlArray(rand(Float32, len))
x = MtlArray(rand(1:3, len))
out = similar(a)
threads = 1024
@device_code_llvm dump_module=true raw=true @metal threads=threads kernel_fma(a, b, x, out)
```
> [Metal] Add correct addrspace to global constants

- src/gcn.jl
- src/interface.jl
- src/ptx.jl
- test/gcn.jl
- test/ptx.jl
- test/runtests.jl
When cross compiling a cuda kernel (for eventual CPU execution) on Apple, GPUCompiler presently errs:
```
Square Kernel: Error During Test at /Users/wmoses/git/Reactant.jl/test/integration/cuda.jl:22
Got exception outside of a @test
ArgumentError: No available targets are compatible with triple "nvptx64-nvidia-cuda"
Stacktrace:
[1] LLVM.Target(; name::Nothing, triple::String)
@ LLVM ~/.julia/packages/LLVM/b3kFs/src/target.jl:33
[2] Target
@ ~/.julia/packages/LLVM/b3kFs/src/target.jl:23 [inlined]
[3] llvm_machine(target::GPUCompiler.PTXCompilerTarget)
@ GPUCompiler ~/.julia/packages/GPUCompiler/Nxf8r/src/ptx.jl:49
[4] macro expansion
@ ~/.julia/packages/GPUCompiler/Nxf8r/src/ptx.jl:140 [inlined]
[5] macro expansion
@ ~/.julia/packages/LLVM/b3kFs/src/base.jl:97 [inlined]
[6] …
```
> Support code emission of nvptx on Apple

- src/jlgen.jl
`MethodError` is pulled in implicitly and we need to disambiguate our usage here
x-ref: https://github.com/JuliaLang/julia/issues/57290
ought to fix the GPUCompiler issue in https://github.com/JuliaLang/julia/issues/57332
> Resolve binding MethodError directly on 1.12

- src/driver.jl
- src/execution.jl
- src/interface.jl
- src/precompile.jl
- src/reflection.jl
- src/rtlib.jl
- src/spirv.jl
- test/helpers/bpf.jl
- test/helpers/gcn.jl
- test/helpers/metal.jl
- test/helpers/native.jl
- test/helpers/ptx.jl
- test/helpers/spirv.jl
- test/metal.jl
- test/native.jl
- test/native/precompile.jl
- test/spirv.jl
The idea behind `CompilerConfig` was that it describes how the compiler should behave, so it should include most of the flags we currently pass to `compile`/`codegen` (e.g., `optimize`, `libraries`, etc).
This should also make caching more correct, as we currently were not including e.g. the optimization level in the logic that loads previous compilation results from the in-memory or disk cache.
This is an API change, so will break back-ends.
EDIT: managed to make it non-breaking.
> Move arguments to compile/codegen into the CompilerConfig struct

- src/mangling.jl
- test/utils.jl
Fixes #671, and adds some tests for each edge-case I found.
I checked some of the logic with the [Itanium ABI specs](https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling) (e.g. `Ptr`), and when possible, if a similarly-defined C++ function would be mangled in the same way.
There might still be some more obscure edge-cases remaining however.
> Fix some edge cases for mangling

- src/irgen.jl
- src/metal.jl
- src/utils.jl
Fixes https://github.com/JuliaGPU/GPUCompiler.jl/issues/680
> Prune unused constant expressions recursively.

- src/jlgen.jl
This depends on https://github.com/JuliaLang/julia/pull/57824 being merged to add a correct version check
> Force emission of const return functions using new API

- src/validation.jl
We may want to clean this up whenever the binding stuff finally stabilizes
> Adapt to latest binding change in 1.12

- src/utils.jl
Fixes #685 
I noticed the testing of these macros was nuked in #658, so I didn't add any tests here, but I'm happy to add something akin to the #685 MWE if desired.
> Avoid closure in @safe_* macros

- src/rtlib.jl
- src/spirv.jl
Helps with https://github.com/JuliaGPU/GPUCompiler.jl/issues/698
> Cache the runtime library in memory.
